role-auth:
  auth-endpoints:
    bearer:
      /training.v1.TrainingService/CreateTraining:
        roles:
          - 1
          - 4
          - 3
      /training.v1.TrainingService/GetTraining:
        roles:
          - 1
          - 4
          - 3
      /training.v1.TrainingService/UpdateTraining:
        roles:
          - 1
          - 4
          - 3
      /training.v1.TrainingService/DeleteTraining:
        roles:
          - 1
          - 4
          - 3
      /users.v1.UserService/GetUserByID:
        roles:
          - 1
          - 4
          - 3
      /users.v1.UserService/DeleteUser:
        roles:
          - 1
          - 4
          - 3
      /users.v1.UserService/UpdateUser:
        roles:
          - 1
          - 4
          - 3

