syntax = "proto3";

package training_booking.v1;

option go_package = "github.com/Antesser/trainingFinder/pkg/api/booking/v1";

import "google/api/annotations.proto";
import  "google/protobuf/timestamp.proto";
import  "proto/protovalidate/buf/validate/validate.proto";
service BookingService {
  rpc BookTraining (BookTrainingRequest) returns (BookTrainingResponse) {
    option (google.api.http) = {
      post: "/api/booking/v1/book-training"
      body: "*"
    };
  }
  rpc ListBookings (ListBookingsRequest) returns (ListBookingsResponse) {
    option (google.api.http) = {
      post: "/api/training/v1/list-bookings"
      body: "*"
    };
  }
  rpc ChangeBookStatus (ChangeBookStatusRequest) returns (ChangeBookStatusResponse) {
    option (google.api.http) = {
      post: "/api/booking/v1/book-status"
      body: "*"
    };
  }
}

message Page{
  uint64 limit = 1;
  uint64 offset = 2;
}


message Booking{
  string id = 1;
  string training_id = 2 ;
  string booked_by = 3 ;
  string status = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp book_from = 6;
  google.protobuf.Timestamp book_to = 7;
}
message BookTrainingRequest {
  string training_id = 1[(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  string user_id = 2[(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  google.protobuf.Timestamp book_from = 3;
  google.protobuf.Timestamp book_to = 4;
}

message BookTrainingResponse {

}

message ListBookingsRequest {
  Page page = 1 [(buf.validate.field).required = true];
  optional Filter filter = 2;
  message Filter{
    optional google.protobuf.Timestamp booked_from = 1;
    optional google.protobuf.Timestamp booked_to = 2;
    optional string trainer_id = 3[(buf.validate.field).string.uuid = true];
  }
}

message ListBookingsResponse {
  repeated Booking bookings = 1;
  bool has_next = 2;
}

message ChangeBookStatusRequest {
  string  status_id = 1[(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  string status = 2[(buf.validate.field).required = true];
}

message ChangeBookStatusResponse {
}

enum BookingStatus {
  BOOKING_STATUS_UNSPECIFIED = 0;
  BOOKING_STATUS_AWAITING_FOR_APPROVAL = 1;
  BOOKING_STATUS_APPROVED = 2;
  BOOKING_STATUS_IN_PROGRESS = 3;
  BOOKING_STATUS_COMPLETED = 4;
  BOOKING_STATUS_CANCELLED = 5;
  BOOKING_STATUS_DECLINED = 6;
}