// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: api/training/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrainingService_CreateTraining_FullMethodName = "/training.v1.TrainingService/CreateTraining"
	TrainingService_DeleteTraining_FullMethodName = "/training.v1.TrainingService/DeleteTraining"
	TrainingService_UpdateTraining_FullMethodName = "/training.v1.TrainingService/UpdateTraining"
	TrainingService_GetTraining_FullMethodName    = "/training.v1.TrainingService/GetTraining"
	TrainingService_ListTrainings_FullMethodName  = "/training.v1.TrainingService/ListTrainings"
)

// TrainingServiceClient is the client API for TrainingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingServiceClient interface {
	CreateTraining(ctx context.Context, in *CreateTrainingRequest, opts ...grpc.CallOption) (*CreateTrainingResponse, error)
	DeleteTraining(ctx context.Context, in *DeleteTrainingRequest, opts ...grpc.CallOption) (*DeleteTrainingResponse, error)
	UpdateTraining(ctx context.Context, in *UpdateTrainingRequest, opts ...grpc.CallOption) (*UpdateTrainingResponse, error)
	GetTraining(ctx context.Context, in *GetTrainingRequest, opts ...grpc.CallOption) (*GetTrainingResponse, error)
	ListTrainings(ctx context.Context, in *ListTrainingsRequest, opts ...grpc.CallOption) (*ListTrainingsResponse, error)
}

type trainingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingServiceClient(cc grpc.ClientConnInterface) TrainingServiceClient {
	return &trainingServiceClient{cc}
}

func (c *trainingServiceClient) CreateTraining(ctx context.Context, in *CreateTrainingRequest, opts ...grpc.CallOption) (*CreateTrainingResponse, error) {
	out := new(CreateTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingService_CreateTraining_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) DeleteTraining(ctx context.Context, in *DeleteTrainingRequest, opts ...grpc.CallOption) (*DeleteTrainingResponse, error) {
	out := new(DeleteTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingService_DeleteTraining_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) UpdateTraining(ctx context.Context, in *UpdateTrainingRequest, opts ...grpc.CallOption) (*UpdateTrainingResponse, error) {
	out := new(UpdateTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingService_UpdateTraining_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) GetTraining(ctx context.Context, in *GetTrainingRequest, opts ...grpc.CallOption) (*GetTrainingResponse, error) {
	out := new(GetTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingService_GetTraining_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) ListTrainings(ctx context.Context, in *ListTrainingsRequest, opts ...grpc.CallOption) (*ListTrainingsResponse, error) {
	out := new(ListTrainingsResponse)
	err := c.cc.Invoke(ctx, TrainingService_ListTrainings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingServiceServer is the server API for TrainingService service.
// All implementations must embed UnimplementedTrainingServiceServer
// for forward compatibility
type TrainingServiceServer interface {
	CreateTraining(context.Context, *CreateTrainingRequest) (*CreateTrainingResponse, error)
	DeleteTraining(context.Context, *DeleteTrainingRequest) (*DeleteTrainingResponse, error)
	UpdateTraining(context.Context, *UpdateTrainingRequest) (*UpdateTrainingResponse, error)
	GetTraining(context.Context, *GetTrainingRequest) (*GetTrainingResponse, error)
	ListTrainings(context.Context, *ListTrainingsRequest) (*ListTrainingsResponse, error)
	mustEmbedUnimplementedTrainingServiceServer()
}

// UnimplementedTrainingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrainingServiceServer struct {
}

func (UnimplementedTrainingServiceServer) CreateTraining(context.Context, *CreateTrainingRequest) (*CreateTrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTraining not implemented")
}
func (UnimplementedTrainingServiceServer) DeleteTraining(context.Context, *DeleteTrainingRequest) (*DeleteTrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTraining not implemented")
}
func (UnimplementedTrainingServiceServer) UpdateTraining(context.Context, *UpdateTrainingRequest) (*UpdateTrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTraining not implemented")
}
func (UnimplementedTrainingServiceServer) GetTraining(context.Context, *GetTrainingRequest) (*GetTrainingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraining not implemented")
}
func (UnimplementedTrainingServiceServer) ListTrainings(context.Context, *ListTrainingsRequest) (*ListTrainingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrainings not implemented")
}
func (UnimplementedTrainingServiceServer) mustEmbedUnimplementedTrainingServiceServer() {}

// UnsafeTrainingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServiceServer will
// result in compilation errors.
type UnsafeTrainingServiceServer interface {
	mustEmbedUnimplementedTrainingServiceServer()
}

func RegisterTrainingServiceServer(s grpc.ServiceRegistrar, srv TrainingServiceServer) {
	s.RegisterService(&TrainingService_ServiceDesc, srv)
}

func _TrainingService_CreateTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).CreateTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_CreateTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).CreateTraining(ctx, req.(*CreateTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_DeleteTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).DeleteTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_DeleteTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).DeleteTraining(ctx, req.(*DeleteTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_UpdateTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).UpdateTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_UpdateTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).UpdateTraining(ctx, req.(*UpdateTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_GetTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).GetTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_GetTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).GetTraining(ctx, req.(*GetTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_ListTrainings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrainingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).ListTrainings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_ListTrainings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).ListTrainings(ctx, req.(*ListTrainingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainingService_ServiceDesc is the grpc.ServiceDesc for TrainingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "training.v1.TrainingService",
	HandlerType: (*TrainingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTraining",
			Handler:    _TrainingService_CreateTraining_Handler,
		},
		{
			MethodName: "DeleteTraining",
			Handler:    _TrainingService_DeleteTraining_Handler,
		},
		{
			MethodName: "UpdateTraining",
			Handler:    _TrainingService_UpdateTraining_Handler,
		},
		{
			MethodName: "GetTraining",
			Handler:    _TrainingService_GetTraining_Handler,
		},
		{
			MethodName: "ListTrainings",
			Handler:    _TrainingService_ListTrainings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/training/v1/service.proto",
}
