// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.5-bufbuild-protocompile-easyp
// source: api/training/v1/service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrainingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrainerId      string                 `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // указываем полный путь до структуры
	EndedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	AdditionalInfo string                 `protobuf:"bytes,5,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTrainingRequest) Reset() {
	*x = CreateTrainingRequest{}
	mi := &file_api_training_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingRequest) ProtoMessage() {}

func (x *CreateTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingRequest.ProtoReflect.Descriptor instead.
func (*CreateTrainingRequest) Descriptor() ([]byte, []int) {
	return file_api_training_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrainingRequest) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *CreateTrainingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTrainingRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateTrainingRequest) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *CreateTrainingRequest) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

type CreateTrainingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainingId    string                 `protobuf:"bytes,1,opt,name=training_id,json=trainingId,proto3" json:"training_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrainingResponse) Reset() {
	*x = CreateTrainingResponse{}
	mi := &file_api_training_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingResponse) ProtoMessage() {}

func (x *CreateTrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingResponse.ProtoReflect.Descriptor instead.
func (*CreateTrainingResponse) Descriptor() ([]byte, []int) {
	return file_api_training_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrainingResponse) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

var File_api_training_v1_service_proto protoreflect.FileDescriptor

const file_api_training_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/training/v1/service.proto\x12\vtraining.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a/proto/protovalidate/buf/validate/validate.proto\"\xfc\x01\n" +
	"\x15CreateTrainingRequest\x12'\n" +
	"\n" +
	"trainer_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\ttrainerId\x12\x1f\n" +
	"\auser_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06userId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12'\n" +
	"\x0fadditional_info\x18\x05 \x01(\tR\x0eadditionalInfo\"9\n" +
	"\x16CreateTrainingResponse\x12\x1f\n" +
	"\vtraining_id\x18\x01 \x01(\tR\n" +
	"trainingId2\x8d\x01\n" +
	"\x0fTrainingService\x12z\n" +
	"\x0eCreateTraining\x12\".training.v1.CreateTrainingRequest\x1a#.training.v1.CreateTrainingResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/training/createB$Z\"trainingFinder/pkg/api/training/v1b\x06proto3"

var (
	file_api_training_v1_service_proto_rawDescOnce sync.Once
	file_api_training_v1_service_proto_rawDescData []byte
)

func file_api_training_v1_service_proto_rawDescGZIP() []byte {
	file_api_training_v1_service_proto_rawDescOnce.Do(func() {
		file_api_training_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_training_v1_service_proto_rawDesc), len(file_api_training_v1_service_proto_rawDesc)))
	})
	return file_api_training_v1_service_proto_rawDescData
}

var file_api_training_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_training_v1_service_proto_goTypes = []any{
	(*CreateTrainingRequest)(nil),  // 0: training.v1.CreateTrainingRequest
	(*CreateTrainingResponse)(nil), // 1: training.v1.CreateTrainingResponse
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_api_training_v1_service_proto_depIdxs = []int32{
	2, // 0: training.v1.CreateTrainingRequest.started_at:type_name -> google.protobuf.Timestamp
	2, // 1: training.v1.CreateTrainingRequest.ended_at:type_name -> google.protobuf.Timestamp
	0, // 2: training.v1.TrainingService.CreateTraining:input_type -> training.v1.CreateTrainingRequest
	1, // 3: training.v1.TrainingService.CreateTraining:output_type -> training.v1.CreateTrainingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_training_v1_service_proto_init() }
func file_api_training_v1_service_proto_init() {
	if File_api_training_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_training_v1_service_proto_rawDesc), len(file_api_training_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_training_v1_service_proto_goTypes,
		DependencyIndexes: file_api_training_v1_service_proto_depIdxs,
		MessageInfos:      file_api_training_v1_service_proto_msgTypes,
	}.Build()
	File_api_training_v1_service_proto = out.File
	file_api_training_v1_service_proto_goTypes = nil
	file_api_training_v1_service_proto_depIdxs = nil
}
