// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/training/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Training with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Training) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Training with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrainingMultiError, or nil
// if none found.
func (m *Training) ValidateAll() error {
	return m.validate(true)
}

func (m *Training) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TrainerId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TrainingValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TrainingValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TrainingValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TrainingValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TrainingValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TrainingValidationError{
				field:  "EndedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AdditionalInfo

	if len(errors) > 0 {
		return TrainingMultiError(errors)
	}

	return nil
}

// TrainingMultiError is an error wrapping multiple validation errors returned
// by Training.ValidateAll() if the designated constraints aren't met.
type TrainingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrainingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrainingMultiError) AllErrors() []error { return m }

// TrainingValidationError is the validation error returned by
// Training.Validate if the designated constraints aren't met.
type TrainingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrainingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrainingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrainingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrainingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrainingValidationError) ErrorName() string { return "TrainingValidationError" }

// Error satisfies the builtin error interface
func (e TrainingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTraining.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrainingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrainingValidationError{}

// Validate checks the field values on CreateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTrainingRequestMultiError, or nil if none found.
func (m *CreateTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainerId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTrainingRequestValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTrainingRequestValidationError{
				field:  "EndedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AdditionalInfo

	if len(errors) > 0 {
		return CreateTrainingRequestMultiError(errors)
	}

	return nil
}

// CreateTrainingRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTrainingRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTrainingRequestMultiError) AllErrors() []error { return m }

// CreateTrainingRequestValidationError is the validation error returned by
// CreateTrainingRequest.Validate if the designated constraints aren't met.
type CreateTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTrainingRequestValidationError) ErrorName() string {
	return "CreateTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTrainingRequestValidationError{}

// Validate checks the field values on CreateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTrainingResponseMultiError, or nil if none found.
func (m *CreateTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateTrainingResponseMultiError(errors)
	}

	return nil
}

// CreateTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTrainingResponseMultiError) AllErrors() []error { return m }

// CreateTrainingResponseValidationError is the validation error returned by
// CreateTrainingResponse.Validate if the designated constraints aren't met.
type CreateTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTrainingResponseValidationError) ErrorName() string {
	return "CreateTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTrainingResponseValidationError{}

// Validate checks the field values on DeleteTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTrainingRequestMultiError, or nil if none found.
func (m *DeleteTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteTrainingRequestMultiError(errors)
	}

	return nil
}

// DeleteTrainingRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteTrainingRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTrainingRequestMultiError) AllErrors() []error { return m }

// DeleteTrainingRequestValidationError is the validation error returned by
// DeleteTrainingRequest.Validate if the designated constraints aren't met.
type DeleteTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTrainingRequestValidationError) ErrorName() string {
	return "DeleteTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTrainingRequestValidationError{}

// Validate checks the field values on DeleteTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTrainingResponseMultiError, or nil if none found.
func (m *DeleteTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTrainingResponseMultiError(errors)
	}

	return nil
}

// DeleteTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTrainingResponseMultiError) AllErrors() []error { return m }

// DeleteTrainingResponseValidationError is the validation error returned by
// DeleteTrainingResponse.Validate if the designated constraints aren't met.
type DeleteTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTrainingResponseValidationError) ErrorName() string {
	return "DeleteTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTrainingResponseValidationError{}

// Validate checks the field values on UpdateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTrainingRequestMultiError, or nil if none found.
func (m *UpdateTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.TrainerId != nil {
		// no validation rules for TrainerId
	}

	if m.UserId != nil {
		// no validation rules for UserId
	}

	if m.StartedAt != nil {

		if all {
			switch v := interface{}(m.GetStartedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateTrainingRequestValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateTrainingRequestValidationError{
						field:  "StartedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateTrainingRequestValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.EndedAt != nil {

		if all {
			switch v := interface{}(m.GetEndedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateTrainingRequestValidationError{
						field:  "EndedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateTrainingRequestValidationError{
						field:  "EndedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetEndedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateTrainingRequestValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.AdditionalInfo != nil {
		// no validation rules for AdditionalInfo
	}

	if len(errors) > 0 {
		return UpdateTrainingRequestMultiError(errors)
	}

	return nil
}

// UpdateTrainingRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateTrainingRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTrainingRequestMultiError) AllErrors() []error { return m }

// UpdateTrainingRequestValidationError is the validation error returned by
// UpdateTrainingRequest.Validate if the designated constraints aren't met.
type UpdateTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTrainingRequestValidationError) ErrorName() string {
	return "UpdateTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTrainingRequestValidationError{}

// Validate checks the field values on UpdateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTrainingResponseMultiError, or nil if none found.
func (m *UpdateTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateTrainingResponseMultiError(errors)
	}

	return nil
}

// UpdateTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTrainingResponseMultiError) AllErrors() []error { return m }

// UpdateTrainingResponseValidationError is the validation error returned by
// UpdateTrainingResponse.Validate if the designated constraints aren't met.
type UpdateTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTrainingResponseValidationError) ErrorName() string {
	return "UpdateTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTrainingResponseValidationError{}

// Validate checks the field values on GetTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrainingRequestMultiError, or nil if none found.
func (m *GetTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetTrainingRequestMultiError(errors)
	}

	return nil
}

// GetTrainingRequestMultiError is an error wrapping multiple validation errors
// returned by GetTrainingRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrainingRequestMultiError) AllErrors() []error { return m }

// GetTrainingRequestValidationError is the validation error returned by
// GetTrainingRequest.Validate if the designated constraints aren't met.
type GetTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrainingRequestValidationError) ErrorName() string {
	return "GetTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrainingRequestValidationError{}

// Validate checks the field values on GetTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrainingResponseMultiError, or nil if none found.
func (m *GetTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTraining()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTrainingResponseValidationError{
					field:  "Training",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTrainingResponseValidationError{
					field:  "Training",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTraining()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTrainingResponseValidationError{
				field:  "Training",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTrainingResponseMultiError(errors)
	}

	return nil
}

// GetTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by GetTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrainingResponseMultiError) AllErrors() []error { return m }

// GetTrainingResponseValidationError is the validation error returned by
// GetTrainingResponse.Validate if the designated constraints aren't met.
type GetTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrainingResponseValidationError) ErrorName() string {
	return "GetTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrainingResponseValidationError{}

// Validate checks the field values on ListTrainingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTrainingsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTrainingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTrainingsRequestMultiError, or nil if none found.
func (m *ListTrainingsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTrainingsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageLimit

	// no validation rules for Offset

	// no validation rules for UserId

	if len(errors) > 0 {
		return ListTrainingsRequestMultiError(errors)
	}

	return nil
}

// ListTrainingsRequestMultiError is an error wrapping multiple validation
// errors returned by ListTrainingsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListTrainingsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTrainingsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTrainingsRequestMultiError) AllErrors() []error { return m }

// ListTrainingsRequestValidationError is the validation error returned by
// ListTrainingsRequest.Validate if the designated constraints aren't met.
type ListTrainingsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTrainingsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTrainingsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTrainingsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTrainingsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTrainingsRequestValidationError) ErrorName() string {
	return "ListTrainingsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTrainingsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTrainingsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTrainingsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTrainingsRequestValidationError{}

// Validate checks the field values on ListTrainingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTrainingsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTrainingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTrainingsResponseMultiError, or nil if none found.
func (m *ListTrainingsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTrainingsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTrainings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTrainingsResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTrainingsResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTrainingsResponseValidationError{
					field:  fmt.Sprintf("Trainings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListTrainingsResponseMultiError(errors)
	}

	return nil
}

// ListTrainingsResponseMultiError is an error wrapping multiple validation
// errors returned by ListTrainingsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListTrainingsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTrainingsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTrainingsResponseMultiError) AllErrors() []error { return m }

// ListTrainingsResponseValidationError is the validation error returned by
// ListTrainingsResponse.Validate if the designated constraints aren't met.
type ListTrainingsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTrainingsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTrainingsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTrainingsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTrainingsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTrainingsResponseValidationError) ErrorName() string {
	return "ListTrainingsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTrainingsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTrainingsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTrainingsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTrainingsResponseValidationError{}
