// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/training/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTrainingRequestMultiError, or nil if none found.
func (m *CreateTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainerId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTrainingRequestValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTrainingRequestValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTrainingRequestValidationError{
				field:  "EndedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AdditionalInfo

	if len(errors) > 0 {
		return CreateTrainingRequestMultiError(errors)
	}

	return nil
}

// CreateTrainingRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTrainingRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTrainingRequestMultiError) AllErrors() []error { return m }

// CreateTrainingRequestValidationError is the validation error returned by
// CreateTrainingRequest.Validate if the designated constraints aren't met.
type CreateTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTrainingRequestValidationError) ErrorName() string {
	return "CreateTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTrainingRequestValidationError{}

// Validate checks the field values on CreateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTrainingResponseMultiError, or nil if none found.
func (m *CreateTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainingId

	if len(errors) > 0 {
		return CreateTrainingResponseMultiError(errors)
	}

	return nil
}

// CreateTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTrainingResponseMultiError) AllErrors() []error { return m }

// CreateTrainingResponseValidationError is the validation error returned by
// CreateTrainingResponse.Validate if the designated constraints aren't met.
type CreateTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTrainingResponseValidationError) ErrorName() string {
	return "CreateTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTrainingResponseValidationError{}
