// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.5-bufbuild-protocompile-easyp
// source: api/users/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_users_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_users_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_service_proto_rawDescGZIP(), []int{1}
}

var File_api_users_v1_service_proto protoreflect.FileDescriptor

const file_api_users_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/users/v1/service.proto\x12\busers.v1\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x14\n" +
	"\x12CreateUserResponse2t\n" +
	"\vUserService\x12e\n" +
	"\n" +
	"CreateUser\x12\x1b.users.v1.CreateUserRequest\x1a\x1c.users.v1.CreateUserResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/users/createB!Z\x1ftrainingFinder/pkg/api/users/v1b\x06proto3"

var (
	file_api_users_v1_service_proto_rawDescOnce sync.Once
	file_api_users_v1_service_proto_rawDescData []byte
)

func file_api_users_v1_service_proto_rawDescGZIP() []byte {
	file_api_users_v1_service_proto_rawDescOnce.Do(func() {
		file_api_users_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)))
	})
	return file_api_users_v1_service_proto_rawDescData
}

var file_api_users_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_users_v1_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: users.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: users.v1.CreateUserResponse
}
var file_api_users_v1_service_proto_depIdxs = []int32{
	0, // 0: users.v1.UserService.CreateUser:input_type -> users.v1.CreateUserRequest
	1, // 1: users.v1.UserService.CreateUser:output_type -> users.v1.CreateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_service_proto_init() }
func file_api_users_v1_service_proto_init() {
	if File_api_users_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_service_proto_depIdxs,
		MessageInfos:      file_api_users_v1_service_proto_msgTypes,
	}.Build()
	File_api_users_v1_service_proto = out.File
	file_api_users_v1_service_proto_goTypes = nil
	file_api_users_v1_service_proto_depIdxs = nil
}
