// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/kafka/v1/kafka.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateTrainingEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTrainingEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTrainingEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTrainingEventMultiError, or nil if none found.
func (m *CreateTrainingEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTrainingEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainingId

	if len(errors) > 0 {
		return CreateTrainingEventMultiError(errors)
	}

	return nil
}

// CreateTrainingEventMultiError is an error wrapping multiple validation
// errors returned by CreateTrainingEvent.ValidateAll() if the designated
// constraints aren't met.
type CreateTrainingEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTrainingEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTrainingEventMultiError) AllErrors() []error { return m }

// CreateTrainingEventValidationError is the validation error returned by
// CreateTrainingEvent.Validate if the designated constraints aren't met.
type CreateTrainingEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTrainingEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTrainingEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTrainingEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTrainingEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTrainingEventValidationError) ErrorName() string {
	return "CreateTrainingEventValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTrainingEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTrainingEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTrainingEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTrainingEventValidationError{}

// Validate checks the field values on DeleteTrainingEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTrainingEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTrainingEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTrainingEventMultiError, or nil if none found.
func (m *DeleteTrainingEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTrainingEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainingId

	if len(errors) > 0 {
		return DeleteTrainingEventMultiError(errors)
	}

	return nil
}

// DeleteTrainingEventMultiError is an error wrapping multiple validation
// errors returned by DeleteTrainingEvent.ValidateAll() if the designated
// constraints aren't met.
type DeleteTrainingEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTrainingEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTrainingEventMultiError) AllErrors() []error { return m }

// DeleteTrainingEventValidationError is the validation error returned by
// DeleteTrainingEvent.Validate if the designated constraints aren't met.
type DeleteTrainingEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTrainingEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTrainingEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTrainingEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTrainingEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTrainingEventValidationError) ErrorName() string {
	return "DeleteTrainingEventValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTrainingEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTrainingEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTrainingEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTrainingEventValidationError{}
