// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.31.1
// source: api/kafka/v1/kafka.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrainingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainingId string `protobuf:"bytes,1,opt,name=training_id,json=trainingId,proto3" json:"training_id,omitempty"`
}

func (x *CreateTrainingEvent) Reset() {
	*x = CreateTrainingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_v1_kafka_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrainingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingEvent) ProtoMessage() {}

func (x *CreateTrainingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_v1_kafka_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingEvent.ProtoReflect.Descriptor instead.
func (*CreateTrainingEvent) Descriptor() ([]byte, []int) {
	return file_api_kafka_v1_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrainingEvent) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

type DeleteTrainingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainingId string `protobuf:"bytes,1,opt,name=training_id,json=trainingId,proto3" json:"training_id,omitempty"`
}

func (x *DeleteTrainingEvent) Reset() {
	*x = DeleteTrainingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_v1_kafka_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrainingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainingEvent) ProtoMessage() {}

func (x *DeleteTrainingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_v1_kafka_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrainingEvent.ProtoReflect.Descriptor instead.
func (*DeleteTrainingEvent) Descriptor() ([]byte, []int) {
	return file_api_kafka_v1_kafka_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTrainingEvent) GetTrainingId() string {
	if x != nil {
		return x.TrainingId
	}
	return ""
}

var File_api_kafka_v1_kafka_proto protoreflect.FileDescriptor

var file_api_kafka_v1_kafka_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x6b,
	0x61, 0x66, 0x6b, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x61, 0x66, 0x6b,
	0x61, 0x2e, 0x76, 0x31, 0x22, 0x36, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x74, 0x65, 0x73, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_kafka_v1_kafka_proto_rawDescOnce sync.Once
	file_api_kafka_v1_kafka_proto_rawDescData = file_api_kafka_v1_kafka_proto_rawDesc
)

func file_api_kafka_v1_kafka_proto_rawDescGZIP() []byte {
	file_api_kafka_v1_kafka_proto_rawDescOnce.Do(func() {
		file_api_kafka_v1_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_kafka_v1_kafka_proto_rawDescData)
	})
	return file_api_kafka_v1_kafka_proto_rawDescData
}

var file_api_kafka_v1_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kafka_v1_kafka_proto_goTypes = []interface{}{
	(*CreateTrainingEvent)(nil), // 0: kafka.v1.CreateTrainingEvent
	(*DeleteTrainingEvent)(nil), // 1: kafka.v1.DeleteTrainingEvent
}
var file_api_kafka_v1_kafka_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kafka_v1_kafka_proto_init() }
func file_api_kafka_v1_kafka_proto_init() {
	if File_api_kafka_v1_kafka_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_kafka_v1_kafka_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrainingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kafka_v1_kafka_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrainingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_kafka_v1_kafka_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kafka_v1_kafka_proto_goTypes,
		DependencyIndexes: file_api_kafka_v1_kafka_proto_depIdxs,
		MessageInfos:      file_api_kafka_v1_kafka_proto_msgTypes,
	}.Build()
	File_api_kafka_v1_kafka_proto = out.File
	file_api_kafka_v1_kafka_proto_rawDesc = nil
	file_api_kafka_v1_kafka_proto_goTypes = nil
	file_api_kafka_v1_kafka_proto_depIdxs = nil
}
