// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	page "github.com/Antesser/trainingFinder/internal/model/page"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	training "github.com/Antesser/trainingFinder/internal/model/training"

	v1 "github.com/Antesser/trainingFinder/pkg/api/training/v1"
)

// TrainingRepository is an autogenerated mock type for the trainingRepository type
type TrainingRepository struct {
	mock.Mock
}

// CreateTraining provides a mock function with given fields: ctx, _a1
func (_m *TrainingRepository) CreateTraining(ctx context.Context, _a1 training.Training) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTraining")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, training.Training) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTraining provides a mock function with given fields: ctx, id
func (_m *TrainingRepository) DeleteTraining(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTraining")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTraining provides a mock function with given fields: ctx, id
func (_m *TrainingRepository) GetTraining(ctx context.Context, id string) (*training.Training, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTraining")
	}

	var r0 *training.Training
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*training.Training, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *training.Training); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*training.Training)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InTx provides a mock function with given fields: ctx, fn
func (_m *TrainingRepository) InTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InTxWithIsoLevel provides a mock function with given fields: ctx, isoLevel, fn
func (_m *TrainingRepository) InTxWithIsoLevel(ctx context.Context, isoLevel pgx.TxIsoLevel, fn func(context.Context) error) error {
	ret := _m.Called(ctx, isoLevel, fn)

	if len(ret) == 0 {
		panic("no return value specified for InTxWithIsoLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxIsoLevel, func(context.Context) error) error); ok {
		r0 = rf(ctx, isoLevel, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListTrainings provides a mock function with given fields: ctx, _a1, filter
func (_m *TrainingRepository) ListTrainings(ctx context.Context, _a1 page.Page, filter v1.Filter) ([]training.Training, bool, error) {
	ret := _m.Called(ctx, _a1, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTrainings")
	}

	var r0 []training.Training
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, page.Page, v1.Filter) ([]training.Training, bool, error)); ok {
		return rf(ctx, _a1, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, page.Page, v1.Filter) []training.Training); ok {
		r0 = rf(ctx, _a1, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]training.Training)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, page.Page, v1.Filter) bool); ok {
		r1 = rf(ctx, _a1, filter)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, page.Page, v1.Filter) error); ok {
		r2 = rf(ctx, _a1, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateTraining provides a mock function with given fields: ctx, updateTraining
func (_m *TrainingRepository) UpdateTraining(ctx context.Context, updateTraining training.UpdateTrainingRequest) error {
	ret := _m.Called(ctx, updateTraining)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTraining")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, training.UpdateTrainingRequest) error); ok {
		r0 = rf(ctx, updateTraining)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrainingRepository creates a new instance of TrainingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrainingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrainingRepository {
	mock := &TrainingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
