// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/booking/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Page with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Page) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Page with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PageMultiError, or nil if none found.
func (m *Page) ValidateAll() error {
	return m.validate(true)
}

func (m *Page) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return PageMultiError(errors)
	}

	return nil
}

// PageMultiError is an error wrapping multiple validation errors returned by
// Page.ValidateAll() if the designated constraints aren't met.
type PageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageMultiError) AllErrors() []error { return m }

// PageValidationError is the validation error returned by Page.Validate if the
// designated constraints aren't met.
type PageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageValidationError) ErrorName() string { return "PageValidationError" }

// Error satisfies the builtin error interface
func (e PageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageValidationError{}

// Validate checks the field values on Booking with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Booking) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Booking with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BookingMultiError, or nil if none found.
func (m *Booking) ValidateAll() error {
	return m.validate(true)
}

func (m *Booking) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TrainingId

	// no validation rules for BookedBy

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBookFrom()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "BookFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "BookFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBookFrom()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "BookFrom",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBookTo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "BookTo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingValidationError{
					field:  "BookTo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBookTo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingValidationError{
				field:  "BookTo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BookingMultiError(errors)
	}

	return nil
}

// BookingMultiError is an error wrapping multiple validation errors returned
// by Booking.ValidateAll() if the designated constraints aren't met.
type BookingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookingMultiError) AllErrors() []error { return m }

// BookingValidationError is the validation error returned by Booking.Validate
// if the designated constraints aren't met.
type BookingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookingValidationError) ErrorName() string { return "BookingValidationError" }

// Error satisfies the builtin error interface
func (e BookingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBooking.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookingValidationError{}

// Validate checks the field values on BookTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BookTrainingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookTrainingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BookTrainingRequestMultiError, or nil if none found.
func (m *BookTrainingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BookTrainingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TrainingId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetBookFrom()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookTrainingRequestValidationError{
					field:  "BookFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookTrainingRequestValidationError{
					field:  "BookFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBookFrom()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookTrainingRequestValidationError{
				field:  "BookFrom",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBookTo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookTrainingRequestValidationError{
					field:  "BookTo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookTrainingRequestValidationError{
					field:  "BookTo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBookTo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookTrainingRequestValidationError{
				field:  "BookTo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BookTrainingRequestMultiError(errors)
	}

	return nil
}

// BookTrainingRequestMultiError is an error wrapping multiple validation
// errors returned by BookTrainingRequest.ValidateAll() if the designated
// constraints aren't met.
type BookTrainingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookTrainingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookTrainingRequestMultiError) AllErrors() []error { return m }

// BookTrainingRequestValidationError is the validation error returned by
// BookTrainingRequest.Validate if the designated constraints aren't met.
type BookTrainingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookTrainingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookTrainingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookTrainingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookTrainingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookTrainingRequestValidationError) ErrorName() string {
	return "BookTrainingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BookTrainingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookTrainingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookTrainingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookTrainingRequestValidationError{}

// Validate checks the field values on BookTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BookTrainingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BookTrainingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BookTrainingResponseMultiError, or nil if none found.
func (m *BookTrainingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BookTrainingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BookTrainingResponseMultiError(errors)
	}

	return nil
}

// BookTrainingResponseMultiError is an error wrapping multiple validation
// errors returned by BookTrainingResponse.ValidateAll() if the designated
// constraints aren't met.
type BookTrainingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookTrainingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookTrainingResponseMultiError) AllErrors() []error { return m }

// BookTrainingResponseValidationError is the validation error returned by
// BookTrainingResponse.Validate if the designated constraints aren't met.
type BookTrainingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookTrainingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookTrainingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookTrainingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookTrainingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookTrainingResponseValidationError) ErrorName() string {
	return "BookTrainingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BookTrainingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookTrainingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookTrainingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookTrainingResponseValidationError{}

// Validate checks the field values on ListBookingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsRequestMultiError, or nil if none found.
func (m *ListBookingsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListBookingsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListBookingsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListBookingsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Filter != nil {

		if all {
			switch v := interface{}(m.GetFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequestValidationError{
						field:  "Filter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListBookingsRequestMultiError(errors)
	}

	return nil
}

// ListBookingsRequestMultiError is an error wrapping multiple validation
// errors returned by ListBookingsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListBookingsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsRequestMultiError) AllErrors() []error { return m }

// ListBookingsRequestValidationError is the validation error returned by
// ListBookingsRequest.Validate if the designated constraints aren't met.
type ListBookingsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsRequestValidationError) ErrorName() string {
	return "ListBookingsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsRequestValidationError{}

// Validate checks the field values on ListBookingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsResponseMultiError, or nil if none found.
func (m *ListBookingsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBookings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsResponseValidationError{
					field:  fmt.Sprintf("Bookings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for HasNext

	if len(errors) > 0 {
		return ListBookingsResponseMultiError(errors)
	}

	return nil
}

// ListBookingsResponseMultiError is an error wrapping multiple validation
// errors returned by ListBookingsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListBookingsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsResponseMultiError) AllErrors() []error { return m }

// ListBookingsResponseValidationError is the validation error returned by
// ListBookingsResponse.Validate if the designated constraints aren't met.
type ListBookingsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsResponseValidationError) ErrorName() string {
	return "ListBookingsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsResponseValidationError{}

// Validate checks the field values on ListBookingsRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListBookingsRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBookingsRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBookingsRequest_FilterMultiError, or nil if none found.
func (m *ListBookingsRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBookingsRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BookedBy

	if m.BookedFrom != nil {

		if all {
			switch v := interface{}(m.GetBookedFrom()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "BookedFrom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "BookedFrom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBookedFrom()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequest_FilterValidationError{
					field:  "BookedFrom",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.BookedTo != nil {

		if all {
			switch v := interface{}(m.GetBookedTo()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "BookedTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListBookingsRequest_FilterValidationError{
						field:  "BookedTo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBookedTo()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListBookingsRequest_FilterValidationError{
					field:  "BookedTo",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListBookingsRequest_FilterMultiError(errors)
	}

	return nil
}

// ListBookingsRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by ListBookingsRequest_Filter.ValidateAll() if
// the designated constraints aren't met.
type ListBookingsRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBookingsRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBookingsRequest_FilterMultiError) AllErrors() []error { return m }

// ListBookingsRequest_FilterValidationError is the validation error returned
// by ListBookingsRequest_Filter.Validate if the designated constraints aren't met.
type ListBookingsRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBookingsRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBookingsRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBookingsRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBookingsRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBookingsRequest_FilterValidationError) ErrorName() string {
	return "ListBookingsRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListBookingsRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBookingsRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBookingsRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBookingsRequest_FilterValidationError{}
