syntax = "proto3";

package auth.v1;

option go_package = "trainingFinder/pkg/api/auth/v1";

import "google/api/annotations.proto";
import  "proto/protovalidate/buf/validate/validate.proto";

service AuthService {
  rpc SignUp (SignUpRequest) returns (SignUpResponse) {
    option (google.api.http) = {
      post: "/api/auth/v1/sign-up"
      body: "*"
    };
  }
  rpc SignIn (SignInRequest) returns (SignInResponse) {
    option (google.api.http) = {
      post: "/api/auth/v1/sign-in"
      body: "*"
    };
  }
  rpc RefreshToken (RefreshTokenRequest) returns (RefreshTokenResponse) {
    option (google.api.http) = {
      post: "/api/auth/v1/refresh-token"
      body: "*"
    };
  }
}
message SignUpRequest {
  string login = 1[(buf.validate.field).required = true];
  string password = 2[(buf.validate.field).required = true];
}

message SignUpResponse {
  string id = 1;
}

message SignInRequest {
  string login = 1[(buf.validate.field).required = true];
  string password = 2[(buf.validate.field).required = true];
}

message SignInResponse {
  string access_token = 1; // везде поудалять нахер RefreshToken
}
message RefreshTokenRequest {
  string refresh_token = 1[(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message RefreshTokenResponse {
  string access_token = 1;
}


